from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


ApplicationsLeasingMethod = Literal["GET", "POST", "DELETE"]
ApplicationsLeasingEndpoint = tuple[ApplicationsLeasingMethod, str]


@dataclass(frozen=True, slots=True)
class ApplicationsLeasingResourceSpec:
    path: str
    client_attr: str
    model_name: str
    fields: tuple[str, ...]
    endpoints: tuple[ApplicationsLeasingEndpoint, ...]

    @property
    def resource_class_name(self) -> str:
        return f"{self.path}Resource"


APPLICATIONS_LEASING_RESOURCE_SPECS = (
    ApplicationsLeasingResourceSpec(
        path="ApplicationDesigns",
        client_attr="application_designs",
        model_name="ApplicationDesign",
        fields=(
            "ApplicationDesignID",
            "DisplayValue",
            "ScriptName",
            "ScriptValue",
            "OrderNumber",
            "IsRequired",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ApplicationDesigns"),
            ("GET", "/ApplicationDesigns/{id}"),
            ("POST", "/ApplicationDesigns"),
            ("DELETE", "/ApplicationDesigns"),
            ("DELETE", "/ApplicationDesigns/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ApplicationFieldLeadSources",
        client_attr="application_field_lead_sources",
        model_name="ApplicationFieldLeadSource",
        fields=(
            "ApplicationFieldLeadSourceID",
            "ApplicationFieldID",
            "ProspectLeadSourceID",
            "DisplayName",
            "SortOrder",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ApplicationFieldLeadSources"),
            ("GET", "/ApplicationFieldLeadSources/{id}"),
            ("POST", "/ApplicationFieldLeadSources"),
            ("DELETE", "/ApplicationFieldLeadSources"),
            ("DELETE", "/ApplicationFieldLeadSources/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ApplicationInfo",
        client_attr="application_info",
        model_name="ApplicationInfoInfo",
        fields=("ProductName", "CurrentVersion", "DisplayVersion", "BuildTimestamp"),
        endpoints=(("GET", "/ApplicationInfo/{id}"),),
    ),
    ApplicationsLeasingResourceSpec(
        path="Applications",
        client_attr="applications",
        model_name="Application",
        fields=(
            "ApplicationID",
            "Status",
            "CreateDate",
            "IPAddress",
            "IsRead",
            "ContactID",
            "AccountID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Applications"),
            ("GET", "/Applications/{id}"),
            ("POST", "/Applications"),
            ("DELETE", "/Applications"),
            ("DELETE", "/Applications/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ApplicationSettings",
        client_attr="application_settings",
        model_name="ApplicationSetting",
        fields=(
            "ApplicationSettingsID",
            "PropertyID",
            "ApplicationTemplateID",
            "ApplicationSubApplicantSetupID",
            "OverrideSystemDefaults",
            "OverridePropertyDefaults",
            "EnableOnlineAppEpay",
            "HavePayleaseManageConvenienceFees",
            "DoNotRequirePayment",
            "PayLaterMessage",
            "ReserveProspectUnit",
            "ACH",
            "DinerClub",
            "VisaMasterCard",
            "AmericanExpress",
            "Discover",
            "ConsentToScreening",
            "AccuracyCertification",
            "ExtendedDisclaimer",
            "RequireDisclaimerForEpayTrans",
            "EpayTransDisclaimer",
            "AllowPrimaryApplicantToPayAll",
            "RunScreening",
            "OverrideSystemDisclaimers",
            "RequireSignatureOnApplication",
            "OverrideSystemUnitToInclude",
            "UnitsToInclude",
            "UseUnitTypeDesc",
            "RequireIncomeVerification",
            "AllowApplicantRefreshExpiredVerificationLink",
            "RefreshExpiredVerificationLinkLimit",
            "IncomeVerificationPageMessage",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ApplicationSettings"),
            ("GET", "/ApplicationSettings/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ApplicationSubApplicantFields",
        client_attr="application_sub_applicant_fields",
        model_name="ApplicationSubApplicantField",
        fields=("ApplicationSubApplicantFieldID", "ApplicationMajorSectionID"),
        endpoints=(
            ("GET", "/ApplicationSubApplicantFields"),
            ("GET", "/ApplicationSubApplicantFields/{id}"),
            ("POST", "/ApplicationSubApplicantFields"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ApplicationSummaries",
        client_attr="application_summaries",
        model_name="ApplicationSummary",
        fields=(
            "ApplicationID",
            "ProspectApplicationID",
            "AccountID",
            "PropertyID",
            "LeasingAgentID",
            "Name",
            "ApplicationDate",
            "AmountPaid",
            "AmountCharged",
            "LastUpdatedDate",
            "CompletedDate",
            "Completed",
            "TotalApplications",
            "ApplicationTemplateID",
            "IsScreened",
            "PhoneNumber",
            "Status",
            "MetaTag",
        ),
        endpoints=(("GET", "/ApplicationSummaries"),),
    ),
    ApplicationsLeasingResourceSpec(
        path="ApplicationTemplates",
        client_attr="application_templates",
        model_name="ApplicationTemplate",
        fields=("ApplicationTemplateID", "Name", "DisplayName", "Description"),
        endpoints=(
            ("GET", "/ApplicationTemplates"),
            ("GET", "/ApplicationTemplates/{id}"),
            ("POST", "/ApplicationTemplates"),
            ("DELETE", "/ApplicationTemplates"),
            ("DELETE", "/ApplicationTemplates/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="EvictionOutcomes",
        client_attr="eviction_outcomes",
        model_name="EvictionOutcome",
        fields=(
            "EvictionOutcomeID",
            "Name",
            "Description",
            "IsActive",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "DisplayValue",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/EvictionOutcomes"),
            ("GET", "/EvictionOutcomes/{id}"),
            ("POST", "/EvictionOutcomes"),
            ("DELETE", "/EvictionOutcomes"),
            ("DELETE", "/EvictionOutcomes/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="EvictionReasons",
        client_attr="eviction_reasons",
        model_name="EvictionReason",
        fields=(
            "EvictionReasonID",
            "Name",
            "Description",
            "IsActive",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/EvictionReasons"),
            ("GET", "/EvictionReasons/{id}"),
            ("POST", "/EvictionReasons"),
            ("DELETE", "/EvictionReasons"),
            ("DELETE", "/EvictionReasons/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="Evictions",
        client_attr="evictions",
        model_name="Eviction",
        fields=(
            "EvictionID",
            "CustomerID",
            "EvictionReasonID",
            "StartDate",
            "EvictionWorkflowID",
            "CurrentStageID",
            "CurrentStageStartDate",
            "NoticeDate",
            "DateSentToAttorney",
            "EvictionFiledDate",
            "CaseNumber",
            "CourtDate",
            "JudgementAmount",
            "VacateDate",
            "WritDate",
            "LockoutDate",
            "EvictionOutcomeID",
            "CloseDate",
            "IsClosed",
            "OriginalIsStopPay",
            "OriginalIsDoNotChargeLateFees",
            "OriginalIsDoNotAcceptChecks",
            "OriginalIsDoNotAllowTWAPayments",
            "OriginalIsDontSendARAutomationNotifications",
            "OriginalIsDoNotAcceptPartialPayments",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Evictions"),
            ("GET", "/Evictions/{id}"),
            ("POST", "/Evictions"),
            ("DELETE", "/Evictions"),
            ("DELETE", "/Evictions/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="EvictionWorkflows",
        client_attr="eviction_workflows",
        model_name="EvictionWorkflow",
        fields=(
            "EvictionWorkflowID",
            "Name",
            "IsActive",
            "StopPartialPaymentsStageID",
            "StopPaymentsStageID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/EvictionWorkflows"),
            ("GET", "/EvictionWorkflows/{id}"),
            ("POST", "/EvictionWorkflows"),
            ("DELETE", "/EvictionWorkflows"),
            ("DELETE", "/EvictionWorkflows/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="EvictionWorkflowStageFields",
        client_attr="eviction_workflow_stage_fields",
        model_name="EvictionWorkflowStageField",
        fields=(
            "EvictionWorkflowStageFieldID",
            "EvictionWorkflowStageID",
            "Label",
            "EvictionSystemFieldID",
            "ColumnSpan",
            "InputFieldType",
            "Script",
            "UserDefinedFieldID",
            "IsReadOnly",
            "SortOrder",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/EvictionWorkflowStageFields"),
            ("GET", "/EvictionWorkflowStageFields/{id}"),
            ("POST", "/EvictionWorkflowStageFields"),
            ("DELETE", "/EvictionWorkflowStageFields"),
            ("DELETE", "/EvictionWorkflowStageFields/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="EvictionWorkflowStages",
        client_attr="eviction_workflow_stages",
        model_name="EvictionWorkflowStage",
        fields=(
            "EvictionWorkflowStageID",
            "EvictionWorkflowID",
            "Name",
            "LetterTemplateID",
            "Instructions",
            "IsLegal",
            "SortOrder",
            "PropertyIDs",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/EvictionWorkflowStages"),
            ("GET", "/EvictionWorkflowStages/{id}"),
            ("POST", "/EvictionWorkflowStages"),
            ("DELETE", "/EvictionWorkflowStages"),
            ("DELETE", "/EvictionWorkflowStages/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="IncomeVerifications",
        client_attr="income_verifications",
        model_name="IncomeVerification",
        fields=(
            "IncomeVerificationID",
            "AccountID",
            "PropertyID",
            "SubmittedDate",
            "OrderCode",
            "ReportCode",
            "ContactID",
            "FirstName",
            "LastName",
            "SocialSecurityNumber",
            "BirthDate",
            "Street",
            "City",
            "State",
            "PostalCode",
            "PhoneNumber",
            "Email",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/IncomeVerifications"),
            ("GET", "/IncomeVerifications/{id}"),
            ("DELETE", "/IncomeVerifications"),
            ("DELETE", "/IncomeVerifications/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="InterestedRentals",
        client_attr="interested_rentals",
        model_name="InterestedRental",
        fields=(
            "InterestedRentalID",
            "EntityTypeID",
            "EntityKeyID",
            "ProspectID",
            "UnitID",
            "IsWaitingList",
            "CreateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/InterestedRentals"),
            ("GET", "/InterestedRentals/{id}"),
            ("POST", "/InterestedRentals"),
            ("DELETE", "/InterestedRentals"),
            ("DELETE", "/InterestedRentals/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="LeaseRenewalIncreaseEntityRoundingSettings",
        client_attr="lease_renewal_increase_entity_rounding_settings",
        model_name="LeaseRenewalIncreaseEntityRoundingSetting",
        fields=(
            "LeaseRenewalIncreaseEntityRoundingSettingID",
            "IsEnabled",
            "PropertyID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "IsOverride",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/LeaseRenewalIncreaseEntityRoundingSettings"),
            ("GET", "/LeaseRenewalIncreaseEntityRoundingSettings/{id}"),
            ("POST", "/LeaseRenewalIncreaseEntityRoundingSettings"),
            ("DELETE", "/LeaseRenewalIncreaseEntityRoundingSettings"),
            ("DELETE", "/LeaseRenewalIncreaseEntityRoundingSettings/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="LeaseRenewalIncreaseOffers",
        client_attr="lease_renewal_increase_offers",
        model_name="LeaseRenewalIncreaseOffer",
        fields=(
            "LeaseRenewalIncreaseOfferID",
            "LeaseRenewalID",
            "Amount",
            "RecurringChargeID",
            "ChargeIncrease",
            "ChargeTypeID",
            "SetUserID",
            "SetDate",
            "ApprovalUserID",
            "ApprovalDate",
            "Comment",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/LeaseRenewalIncreaseOffers"),
            ("GET", "/LeaseRenewalIncreaseOffers/{id}"),
            ("POST", "/LeaseRenewalIncreaseOffers"),
            ("DELETE", "/LeaseRenewalIncreaseOffers"),
            ("DELETE", "/LeaseRenewalIncreaseOffers/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="LeaseRenewals",
        client_attr="lease_renewals",
        model_name="LeaseRenewal",
        fields=(
            "LeaseRenewalID",
            "ParentLeaseID",
            "UnitID",
            "LeaseTermID",
            "LeaseLength",
            "SignDate",
            "StartDate",
            "EndDate",
            "DefaultCommercialExpensePercentage",
            "DefaultCommercialExpenseAdminPercentage",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "SignableDocumentStatus",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/LeaseRenewals"),
            ("GET", "/LeaseRenewals/{id}"),
            ("POST", "/LeaseRenewals"),
            ("DELETE", "/LeaseRenewals"),
            ("DELETE", "/LeaseRenewals/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="LeaseTermEntityDifferentials",
        client_attr="lease_term_entity_differentials",
        model_name="LeaseTermEntityDifferential",
        fields=(
            "LeaseTermEntityDifferentialID",
            "LeaseTermID",
            "PropertyID",
            "Differential",
            "IsDifferentialPercentage",
            "EnableRentOffset",
            "IsAppliedToORI",
            "IsAppliedToAssets",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/LeaseTermEntityDifferentials"),
            ("GET", "/LeaseTermEntityDifferentials/{id}"),
            ("POST", "/LeaseTermEntityDifferentials"),
            ("DELETE", "/LeaseTermEntityDifferentials"),
            ("DELETE", "/LeaseTermEntityDifferentials/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="LeaseTerms",
        client_attr="lease_terms",
        model_name="LeaseTerm",
        fields=("LeaseTermID", "LeaseTerm"),
        endpoints=(
            ("GET", "/LeaseTerms"),
            ("GET", "/LeaseTerms/{id}"),
            ("POST", "/LeaseTerms"),
            ("DELETE", "/LeaseTerms"),
            ("DELETE", "/LeaseTerms/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="MarketRents",
        client_attr="market_rents",
        model_name="MarketRent",
        fields=(
            "MarketRentID",
            "UnitID",
            "Amount",
            "Comment",
            "FromDate",
            "ToDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/MarketRents"),
            ("GET", "/MarketRents/{id}"),
            ("POST", "/MarketRents"),
            ("DELETE", "/MarketRents"),
            ("DELETE", "/MarketRents/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="OnlineBookingMarketingOptions",
        client_attr="online_booking_marketing_options",
        model_name="OnlineBookingMarketingOption",
        fields=(
            "OnlineBookingMarketingOptionID",
            "PropertyID",
            "UseDefault",
            "ParentID",
            "Description",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/OnlineBookingMarketingOptions"),
            ("GET", "/OnlineBookingMarketingOptions/{id}"),
            ("POST", "/OnlineBookingMarketingOptions"),
            ("DELETE", "/OnlineBookingMarketingOptions"),
            ("DELETE", "/OnlineBookingMarketingOptions/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="Pets",
        client_attr="pets",
        model_name="Pet",
        fields=("PetID", "Name", "Description"),
        endpoints=(
            ("GET", "/Pets"),
            ("GET", "/Pets/{id}"),
            ("POST", "/Pets"),
            ("DELETE", "/Pets"),
            ("DELETE", "/Pets/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="PetTypes",
        client_attr="pet_types",
        model_name="PetType",
        fields=("PetTypeID", "Name", "Description"),
        endpoints=(
            ("GET", "/PetTypes"),
            ("GET", "/PetTypes/{id}"),
            ("POST", "/PetTypes"),
            ("DELETE", "/PetTypes"),
            ("DELETE", "/PetTypes/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="PromotionPeriods",
        client_attr="promotion_periods",
        model_name="PromotionPeriod",
        fields=(
            "PromotionPeriodID",
            "LeaseID",
            "StartDate",
            "EndDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/PromotionPeriods"),
            ("GET", "/PromotionPeriods/{id}"),
            ("POST", "/PromotionPeriods"),
            ("DELETE", "/PromotionPeriods"),
            ("DELETE", "/PromotionPeriods/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectApplications",
        client_attr="prospect_applications",
        model_name="ProspectApplication",
        fields=(
            "ProspectApplicationID",
            "ApplicationTemplateID",
            "AccountID",
            "WebUserAccountID",
            "ContactID",
            "PropertyID",
            "UnitTypeID",
            "UnitID",
            "IPAddress",
            "WaiverText",
            "EsignCheckboxText",
            "ConsentToScreenCheckboxText",
            "EpayTransactionText",
            "EpayTranID",
            "ApplicationSubmissionDate",
            "IsTemplateLocked",
            "DisclaimerSignature",
            "DisclaimerSignatureTimeStamp",
            "CreateDate",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ProspectApplications"),
            ("GET", "/ProspectApplications/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectApplicationTemplateFields",
        client_attr="prospect_application_template_fields",
        model_name="ProspectApplicationTemplateField",
        fields=(
            "ApplicationFieldID",
            "ApplicationMinorSectionID",
            "LabelText",
            "HelpText",
            "ColumnSpan",
            "MatchToID",
            "MatchToHandlerID",
            "DependentApplicationFieldID",
            "IsRequired",
            "SortOrder",
            "AllowAnotherChoice",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ProspectApplicationTemplateFields"),
            ("GET", "/ProspectApplicationTemplateFields/{id}"),
            ("POST", "/ProspectApplicationTemplateFields"),
            ("DELETE", "/ProspectApplicationTemplateFields"),
            ("DELETE", "/ProspectApplicationTemplateFields/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectApplicationTemplateMajorSections",
        client_attr="prospect_application_template_major_sections",
        model_name="ProspectApplicationTemplateMajorSection",
        fields=(),
        endpoints=(
            ("GET", "/ProspectApplicationTemplateMajorSections"),
            ("GET", "/ProspectApplicationTemplateMajorSections/{id}"),
            ("POST", "/ProspectApplicationTemplateMajorSections"),
            ("DELETE", "/ProspectApplicationTemplateMajorSections"),
            ("DELETE", "/ProspectApplicationTemplateMajorSections/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectApplicationTemplateMinorSections",
        client_attr="prospect_application_template_minor_sections",
        model_name="ProspectApplicationTemplateMinorSection",
        fields=(
            "ApplicationMinorSectionID",
            "ApplicationMajorSectionID",
            "Title",
            "TitleBinaryFileID",
            "Text",
            "TextBinaryFileID",
            "HelpText",
            "NumberOfColumns",
            "WrapAlignment",
            "SortOrder",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ProspectApplicationTemplateMinorSections"),
            ("GET", "/ProspectApplicationTemplateMinorSections/{id}"),
            ("POST", "/ProspectApplicationTemplateMinorSections"),
            ("DELETE", "/ProspectApplicationTemplateMinorSections"),
            ("DELETE", "/ProspectApplicationTemplateMinorSections/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectApplicationTemplates",
        client_attr="prospect_application_templates",
        model_name="ProspectApplicationTemplate",
        fields=("ApplicationTemplateID", "Name", "DisplayName", "Description"),
        endpoints=(
            ("GET", "/ProspectApplicationTemplates"),
            ("GET", "/ProspectApplicationTemplates/{id}"),
            ("POST", "/ProspectApplicationTemplates"),
            ("DELETE", "/ProspectApplicationTemplates"),
            ("DELETE", "/ProspectApplicationTemplates/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectLostReasons",
        client_attr="prospect_lost_reasons",
        model_name="ProspectLostReason",
        fields=(
            "ProspectLostReasonID",
            "Name",
            "Description",
            "IsActive",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ProspectLostReasons"),
            ("GET", "/ProspectLostReasons/{id}"),
            ("POST", "/ProspectLostReasons"),
            ("DELETE", "/ProspectLostReasons"),
            ("DELETE", "/ProspectLostReasons/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectStages",
        client_attr="prospect_stages",
        model_name="ProspectStage",
        fields=(
            "ProspectStageID",
            "Name",
            "Description",
            "IsActive",
            "HasScreeningDecisionsWhichPrevent",
            "PreventedByLaterTrigger",
            "SortOrder",
            "FollowUpDays",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ProspectStages"),
            ("GET", "/ProspectStages/{id}"),
            ("POST", "/ProspectStages"),
            ("DELETE", "/ProspectStages"),
            ("DELETE", "/ProspectStages/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ProspectSubApplicantDetails",
        client_attr="prospect_sub_applicant_details",
        model_name="ProspectSubApplicantDetail",
        fields=(
            "ProspectSubApplicantDetailsID",
            "ProspectApplicationID",
            "PrimaryProspectApplicationID",
            "ApplicationSubApplicantSetupID",
            "FullName",
            "EmailAddress",
            "IsFromPrimaryApplication",
            "IsChargeAdded",
            "ParentProspectApplicationID",
            "SubApplicantContactID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ProspectSubApplicantDetails"),
            ("GET", "/ProspectSubApplicantDetails/{id}"),
            ("POST", "/ProspectSubApplicantDetails"),
            ("DELETE", "/ProspectSubApplicantDetails"),
            ("DELETE", "/ProspectSubApplicantDetails/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="RateDiscounts",
        client_attr="rate_discounts",
        model_name="RateDiscount",
        fields=(
            "RateDiscountID",
            "Name",
            "PropertyID",
            "Amount",
            "IsPercent",
            "ChargeTypeID",
            "IsMaxNightsEnabled",
            "MaxNights",
            "IsGuestAllowedToSelectFromPortal",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/RateDiscounts"),
            ("GET", "/RateDiscounts/{id}"),
            ("POST", "/RateDiscounts"),
            ("DELETE", "/RateDiscounts"),
            ("DELETE", "/RateDiscounts/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="Rates",
        client_attr="rates",
        model_name="Rate",
        fields=(
            "RateID",
            "Name",
            "RateScheduleID",
            "UnitID",
            "SiteGroupID",
            "ChargeTypeID",
            "IsDynamicRatesEnabled",
            "IsNightlyRateFlat",
            "NightlyFlatRate",
            "RateMonday",
            "RateTuesday",
            "RateWednesday",
            "RateThursday",
            "RateFriday",
            "RateSaturday",
            "RateSunday",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Rates"),
            ("GET", "/Rates/{id}"),
            ("POST", "/Rates"),
            ("DELETE", "/Rates"),
            ("DELETE", "/Rates/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="RateSchedules",
        client_attr="rate_schedules",
        model_name="RateSchedule",
        fields=(
            "RateScheduleID",
            "PropertyID",
            "CreateUserID",
            "UpdateUserID",
            "ConcurrencyID",
            "Name",
            "StartDate",
            "EndDate",
            "CreateDate",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/RateSchedules"),
            ("GET", "/RateSchedules/{id}"),
            ("POST", "/RateSchedules"),
            ("DELETE", "/RateSchedules"),
            ("DELETE", "/RateSchedules/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="RevenuePricing",
        client_attr="revenue_pricing",
        model_name="RevenuePricing",
        fields=(
            "RevenuePricingID",
            "ParentID",
            "PropertyID",
            "LeaseTerm",
            "BaseRent",
            "Concession",
            "EffectiveRent",
            "ConcessionType",
            "ConcessionValue",
            "StartDate",
            "EndDate",
            "Available",
            "DiscountedConcession",
            "MoveInRate",
            "PostDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/RevenuePricing"),
            ("GET", "/RevenuePricing/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="RevenueRenewals",
        client_attr="revenue_renewals",
        model_name="RevenueRenewal",
        fields=(
            "RevenueRenewalID",
            "TenantID",
            "UnitID",
            "UnitTypeID",
            "PropertyID",
            "AmenityValue",
            "OriginalMoveInDate",
            "RenewalDate",
            "CurrentLeaseTerm",
            "LeaseType",
            "PerceivedRent",
            "MarketRent",
            "HasGivenNotice",
            "PostDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/RevenueRenewals"),
            ("GET", "/RevenueRenewals/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ScreeningCredentials",
        client_attr="screening_credentials",
        model_name="ScreeningCredential",
        fields=("ScreeningCredentialID", "UserName", "PropertyID", "MetaTag"),
        endpoints=(
            ("GET", "/ScreeningCredentials"),
            ("GET", "/ScreeningCredentials/{id}"),
            ("POST", "/ScreeningCredentials"),
            ("DELETE", "/ScreeningCredentials"),
            ("DELETE", "/ScreeningCredentials/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ScreeningDetails",
        client_attr="screening_details",
        model_name="ScreeningDetail",
        fields=(
            "ScreeningDetailID",
            "ScreeningID",
            "ContactID",
            "DecisionText",
            "FirstName",
            "MiddleName",
            "LastName",
            "PhoneNumber",
            "SocialSecurityNumber",
            "BirthDate",
            "AnnualIncome",
            "Street",
            "City",
            "State",
            "PostalCode",
            "AdditionalMappedFields",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ScreeningDetails"),
            ("GET", "/ScreeningDetails/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ScreeningResponseFactors",
        client_attr="screening_response_factors",
        model_name="ScreeningResponseFactor",
        fields=("ScreeningResponseFactorID", "ScreeningResponseID", "Factor", "MetaTag"),
        endpoints=(
            ("GET", "/ScreeningResponseFactors"),
            ("GET", "/ScreeningResponseFactors/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ScreeningResponses",
        client_attr="screening_responses",
        model_name="ScreeningResponse",
        fields=(),
        endpoints=(
            ("GET", "/ScreeningResponses"),
            ("GET", "/ScreeningResponses/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="Screenings",
        client_attr="screenings",
        model_name="Screening",
        fields=(
            "ScreeningID",
            "AccountID",
            "Regarding",
            "Date",
            "Type",
            "UserID",
            "PropertyID",
            "UpgradeUserID",
            "FileID",
            "SubmittedDate",
            "RentAmount",
            "ScreeningName",
            "Options",
            "UpgradeDate",
            "Protected",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Screenings"),
            ("GET", "/Screenings/{id}"),
            ("DELETE", "/Screenings"),
            ("DELETE", "/Screenings/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ScreeningSettings",
        client_attr="screening_settings",
        model_name="ScreeningSetting",
        fields=(
            "ScreeningSettingID",
            "PropertyID",
            "IsDSReport",
            "IsTransunion",
            "IsEquifax",
            "IsExperian",
            "IsAmRent",
            "IsBundledScreening",
            "IsCrossCheck",
            "IsDecisionCriminalOnly",
            "IsDecisionEvictionsOnly",
            "IsInfileCriminalOnly",
            "IsInfileEvictionsOnly",
            "IsRPCReport",
            "MinimumDecision",
            "IsInherited",
            "ParentID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ScreeningSettings"),
            ("GET", "/ScreeningSettings/{id}"),
            ("POST", "/ScreeningSettings"),
            ("DELETE", "/ScreeningSettings"),
            ("DELETE", "/ScreeningSettings/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ScreeningUpgrades",
        client_attr="screening_upgrades",
        model_name="ScreeningUpgrade",
        fields=(
            "ScreeningUpgradeID",
            "ScreeningID",
            "RequestingUserName",
            "EmailAddress",
            "PhoneNumber",
            "FaxNumber",
            "IsEmailReport",
            "IsFaxReport",
            "CreateDate",
            "CreateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ScreeningUpgrades"),
            ("GET", "/ScreeningUpgrades/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ShortTermRentalOnlineBookingSettings",
        client_attr="short_term_rental_online_booking_settings",
        model_name="ShortTermRentalOnlineBookingSetting",
        fields=(
            "ShortTermRentalOnlineBookingSettingID",
            "PropertyID",
            "IsAskGuestNumberOfChildren",
            "IsShowInteractiveMapView",
            "BirdsEyeViewMapID",
            "IsOverrideGuestInfoSystemWebPreferences",
            "IsRequireVehicleMakeModel",
            "IsRequireVehicleLicense",
            "IsRequireVehicleYear",
            "IsAllowAdditionalVehicles",
            "IsLeadSourcesEnabled",
            "IsOverrideSettingsSystemWebPreferences",
            "IsCreateTenantAccount",
            "NumberDaysInFuture",
            "ReservationCutoffDate",
            "IsAllowSameDayBookings",
            "NumberDaysInAdvanceRequired",
            "IsMinimumNightsAllowed",
            "NumberMinimumNightsAllowed",
            "MessageMinimumNightsAllowed",
            "IsMaximumNightsAllowed",
            "NumberMaximumNightsAllowed",
            "MessageMaximumNightsAllowed",
            "IsDisplayApplyNowButton",
            "BookingSuccessMessage",
            "TermsAndConditions",
            "IsRestrictRVs",
            "RestrictedRVAge",
            "RVExceedsAgeMessage",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ShortTermRentalPaymentPolicyID",
            "SiteHeaderColorHex",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ShortTermRentalOnlineBookingSettings"),
            ("GET", "/ShortTermRentalOnlineBookingSettings/{id}"),
            ("POST", "/ShortTermRentalOnlineBookingSettings"),
            ("DELETE", "/ShortTermRentalOnlineBookingSettings"),
            ("DELETE", "/ShortTermRentalOnlineBookingSettings/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ShortTermRentalPaymentPolicies",
        client_attr="short_term_rental_payment_policies",
        model_name="ShortTermRentalPaymentPolicy",
        fields=(
            "ShortTermRentalPaymentPolicyID",
            "Name",
            "IsActive",
            "DueAtBooking",
            "IsPercent",
            "RemainderDueDaysBeforeArrival",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ShortTermRentalPaymentPolicies"),
            ("GET", "/ShortTermRentalPaymentPolicies/{id}"),
            ("POST", "/ShortTermRentalPaymentPolicies"),
            ("DELETE", "/ShortTermRentalPaymentPolicies"),
            ("DELETE", "/ShortTermRentalPaymentPolicies/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="ShortTermReservations",
        client_attr="short_term_reservations",
        model_name="ShortTermReservation",
        fields=(
            "ShortTermReservationID",
            "LeaseID",
            "AccountID",
            "NumberNights",
            "NumberAdults",
            "NumberChildren",
            "NumberPets",
            "NumberVehicles",
            "Comment",
            "IsLongTermRental",
            "CheckInDate",
            "CheckOutDate",
            "ConfirmationNumber",
            "ProspectLeadSourceID",
            "AmountDueAtBooking",
            "RemainingBalanceDueDate",
            "IsLocked",
            "TotalAmountDue",
            "RemainingBalance",
            "ArrivalDate",
            "DepartureDate",
            "PropertyID",
            "UnitID",
            "CheckInUserID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "PromotionID",
            "RateDiscountID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ShortTermReservations"),
            ("GET", "/ShortTermReservations/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="TenantStatementAutomatedPostingSettings",
        client_attr="tenant_statement_automated_posting_settings",
        model_name="TenantStatementAutomatedPostingSetting",
        fields=(
            "TenantStatementAutomatedPostingSettingID",
            "Subject",
            "IsHtml",
            "EmailBodyText",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "LetterTemplateID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/TenantStatementAutomatedPostingSettings"),
            ("GET", "/TenantStatementAutomatedPostingSettings/{id}"),
            ("POST", "/TenantStatementAutomatedPostingSettings"),
            ("DELETE", "/TenantStatementAutomatedPostingSettings"),
            ("DELETE", "/TenantStatementAutomatedPostingSettings/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="TenantStatementAutomations",
        client_attr="tenant_statement_automations",
        model_name="TenantStatementAutomation",
        fields=(
            "TenantStatementAutomationID",
            "Name",
            "IsActive",
            "RunDay",
            "NotificationEmail",
            "IncludeDetails",
            "AttachToHistory",
            "HistoryCategoryID",
            "CustomFormID",
            "IsPrimaryContact",
            "IsPast",
            "IsCurrent",
            "IsFuture",
            "FromDate",
            "ToDate",
            "PropertyGroupID",
            "AddressTypeID",
            "ShowUnpostedPerDayLateFees",
            "ShowDailyInterestLoans",
            "ShowMeterReadings",
            "ShowCalculationDetails",
            "UseAccountGroups",
            "Comment",
            "StartDate",
            "EndDate",
            "ExcludeZeroes",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/TenantStatementAutomations"),
            ("GET", "/TenantStatementAutomations/{id}"),
            ("POST", "/TenantStatementAutomations"),
            ("DELETE", "/TenantStatementAutomations"),
            ("DELETE", "/TenantStatementAutomations/{id}"),
        ),
    ),
    ApplicationsLeasingResourceSpec(
        path="UnitStatusTypes",
        client_attr="unit_status_types",
        model_name="UnitStatusType",
        fields=("UnitStatusTypeID", "Name", "Description"),
        endpoints=(
            ("GET", "/UnitStatusTypes"),
            ("GET", "/UnitStatusTypes/{id}"),
            ("POST", "/UnitStatusTypes"),
            ("DELETE", "/UnitStatusTypes"),
            ("DELETE", "/UnitStatusTypes/{id}"),
        ),
    ),
)

APPLICATIONS_LEASING_MODEL_NAMES = tuple(dict.fromkeys(spec.model_name for spec in APPLICATIONS_LEASING_RESOURCE_SPECS))
APPLICATIONS_LEASING_RESOURCE_CLASS_NAMES = tuple(
    spec.resource_class_name for spec in APPLICATIONS_LEASING_RESOURCE_SPECS
)

__all__ = [
    "APPLICATIONS_LEASING_MODEL_NAMES",
    "APPLICATIONS_LEASING_RESOURCE_CLASS_NAMES",
    "APPLICATIONS_LEASING_RESOURCE_SPECS",
    "ApplicationsLeasingEndpoint",
    "ApplicationsLeasingMethod",
    "ApplicationsLeasingResourceSpec",
]
