from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


MaintenanceAssetsInspectionsServiceMethod = Literal["GET", "POST", "DELETE"]
MaintenanceAssetsInspectionsServiceEndpoint = tuple[MaintenanceAssetsInspectionsServiceMethod, str]


@dataclass(frozen=True, slots=True)
class MaintenanceAssetsInspectionsServiceResourceSpec:
    path: str
    client_attr: str
    model_name: str
    fields: tuple[str, ...]
    endpoints: tuple[MaintenanceAssetsInspectionsServiceEndpoint, ...]

    @property
    def resource_class_name(self) -> str:
        return f"{self.path}Resource"


MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_RESOURCE_SPECS = (
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="AssetManufacturers",
        client_attr="asset_manufacturers",
        model_name="AssetManufacturer",
        fields=("AssetManufacturerID", "Name"),
        endpoints=(
            ("GET", "/AssetManufacturers"),
            ("GET", "/AssetManufacturers/{id}"),
            ("POST", "/AssetManufacturers"),
            ("DELETE", "/AssetManufacturers"),
            ("DELETE", "/AssetManufacturers/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="Assets",
        client_attr="assets",
        model_name="Asset",
        fields=(
            "AssetID",
            "AssetTag",
            "ModelNumber",
            "SerialNumber",
            "PurchaseDate",
            "ServiceStartDate",
            "ServiceEndDate",
            "PurchasePrice",
            "PayeeAccountID",
            "SalePrice",
            "Dimensions",
            "Bedrooms",
            "Bathrooms",
            "SquareFootage",
            "VendorID",
            "AssetManufacturerID",
            "AssetTypeID",
            "MaintenancePeriod",
            "LastMaintenanceDate",
            "NextMaintenanceDate",
            "WarrantyInfo",
            "WarrantyExpirationDate",
            "HasServiceAgreement",
            "ServiceAgreementExpiration",
            "Comment",
            "FinancialPropertyID",
            "FinancialUnitID",
            "ManufactureDate",
            "IsTrackingFinancials",
            "IsAllowLeasing",
            "DefaultRent",
            "IsActive",
            "Age",
            "ServiceLength",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "AssetWorkflowID",
            "LienHolder",
        ),
        endpoints=(
            ("GET", "/Assets"),
            ("GET", "/Assets/{id}"),
            ("POST", "/Assets"),
            ("DELETE", "/Assets"),
            ("DELETE", "/Assets/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="AssetStatus",
        client_attr="asset_status",
        model_name="AssetStatus",
        fields=("AssetStatusID", "Name"),
        endpoints=(
            ("GET", "/AssetStatus"),
            ("GET", "/AssetStatus/{id}"),
            ("POST", "/AssetStatus"),
            ("DELETE", "/AssetStatus"),
            ("DELETE", "/AssetStatus/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="AssetStatusHistory",
        client_attr="asset_status_history",
        model_name="AssetStatusHistory",
        fields=(
            "AssetStatusHistoryID",
            "AssetID",
            "AssetStatusID",
            "PropertyID",
            "UnitID",
            "Comment",
            "Duration",
            "CreateUserID",
            "UpdateUserID",
            "FromDate",
            "ToDate",
            "CreateDate",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(("GET", "/AssetStatusHistory"), ("GET", "/AssetStatusHistory/{id}")),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="AssetStatusWorkflows",
        client_attr="asset_status_workflows",
        model_name="AssetStatusWorkflow",
        fields=(
            "AssetStatusWorkflowID",
            "Name",
            "Description",
            "IsActive",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/AssetStatusWorkflows"),
            ("GET", "/AssetStatusWorkflows/{id}"),
            ("POST", "/AssetStatusWorkflows"),
            ("DELETE", "/AssetStatusWorkflows"),
            ("DELETE", "/AssetStatusWorkflows/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="AssetTitleStatuss",
        client_attr="asset_title_statuses",
        model_name="AssetTitleStatus",
        fields=(
            "AssetTitleStatusID",
            "Name",
            "Description",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/AssetTitleStatuss"),
            ("GET", "/AssetTitleStatuss/{id}"),
            ("POST", "/AssetTitleStatuss"),
            ("DELETE", "/AssetTitleStatuss"),
            ("DELETE", "/AssetTitleStatuss/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="AssetTypes",
        client_attr="asset_types",
        model_name="AssetType",
        fields=("AssetTypeID", "Name", "Description", "IsHome"),
        endpoints=(
            ("GET", "/AssetTypes"),
            ("GET", "/AssetTypes/{id}"),
            ("POST", "/AssetTypes"),
            ("DELETE", "/AssetTypes"),
            ("DELETE", "/AssetTypes/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="Estimates",
        client_attr="estimates",
        model_name="Estimate",
        fields=(
            "EstimateID",
            "Reference",
            "EstimateNumber",
            "AccountID",
            "SalesRepresentativeID",
            "IssueDate",
            "IsActive",
            "PropertyID",
            "TaxRate",
            "IsTaxable",
            "TaxTypeID",
            "Interest",
            "TotalValue",
            "Comments",
            "FromAddress",
            "ToAddress",
            "ApprovedRejectedBy",
            "ApprovedRejectedOn",
            "OwnerSignature",
            "ExpirationDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "PurchaseOrderID",
            "InvoiceID",
            "ServiceManagerIssueID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Estimates"),
            ("GET", "/Estimates/{id}"),
            ("POST", "/Estimates"),
            ("DELETE", "/Estimates"),
            ("DELETE", "/Estimates/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionAreaItems",
        client_attr="inspection_area_items",
        model_name="InspectionAreaItem",
        fields=(
            "InspectionAreaItemID",
            "InspectionAreaID",
            "Name",
            "SortOrder",
            "Note",
            "StatusID",
            "Status",
            "IsActionItem",
            "IsSevere",
            "IsReviewNeeded",
            "Directive",
            "IsAdhoc",
            "IsManagementOnly",
            "InspectorHelpText",
            "TenantHelpText",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/InspectionAreaItems"),
            ("GET", "/InspectionAreaItems/{id}"),
            ("POST", "/InspectionAreaItems"),
            ("DELETE", "/InspectionAreaItems"),
            ("DELETE", "/InspectionAreaItems/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionAreas",
        client_attr="inspection_areas",
        model_name="InspectionArea",
        fields=(
            "InspectionAreaID",
            "InspectionID",
            "InspectionVideoFileID",
            "Name",
            "VideoInspectionURL",
            "IsCustomURL",
            "SortOrder",
            "WebUserID",
            "LastInteraction",
            "InspectorHelpText",
            "TenantHelpText",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/InspectionAreas"),
            ("GET", "/InspectionAreas/{id}"),
            ("POST", "/InspectionAreas"),
            ("DELETE", "/InspectionAreas"),
            ("DELETE", "/InspectionAreas/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="Inspections",
        client_attr="inspections",
        model_name="Inspection",
        fields=("InspectionID", "Description", "InspectorID", "InspectionStatusID", "CompletionDate"),
        endpoints=(
            ("GET", "/Inspections"),
            ("GET", "/Inspections/{id}"),
            ("POST", "/Inspections"),
            ("DELETE", "/Inspections"),
            ("DELETE", "/Inspections/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionStatuss",
        client_attr="inspection_statuses",
        model_name="InspectionStatus",
        fields=(
            "InspectionStatusID",
            "Name",
            "IsFinalStatus",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(("GET", "/InspectionStatuss"), ("GET", "/InspectionStatuss/{id}")),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionTemplateAreaItems",
        client_attr="inspection_template_area_items",
        model_name="InspectionTemplateAreaItem",
        fields=(
            "InspectionTemplateAreaItemID",
            "InspectionTemplateAreaID",
            "Name",
            "SortOrder",
            "IsManagementOnly",
            "InspectorHelpText",
            "TenantHelpText",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/InspectionTemplateAreaItems"),
            ("GET", "/InspectionTemplateAreaItems/{id}"),
            ("POST", "/InspectionTemplateAreaItems"),
            ("DELETE", "/InspectionTemplateAreaItems"),
            ("DELETE", "/InspectionTemplateAreaItems/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionTemplateAreas",
        client_attr="inspection_template_areas",
        model_name="InspectionTemplateArea",
        fields=(
            "InspectionTemplateAreaID",
            "InspectionTemplateID",
            "Name",
            "SortOrder",
            "IsManagementOnly",
            "InspectorHelpText",
            "TenantHelpText",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/InspectionTemplateAreas"),
            ("GET", "/InspectionTemplateAreas/{id}"),
            ("POST", "/InspectionTemplateAreas"),
            ("DELETE", "/InspectionTemplateAreas"),
            ("DELETE", "/InspectionTemplateAreas/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionTemplates",
        client_attr="inspection_templates",
        model_name="InspectionTemplate",
        fields=("InspectionTemplateID", "Name"),
        endpoints=(
            ("GET", "/InspectionTemplates"),
            ("GET", "/InspectionTemplates/{id}"),
            ("POST", "/InspectionTemplates"),
            ("DELETE", "/InspectionTemplates"),
            ("DELETE", "/InspectionTemplates/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="InspectionTypes",
        client_attr="inspection_types",
        model_name="InspectionType",
        fields=(
            "InspectionTypeID",
            "Name",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "SortOrder",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/InspectionTypes"),
            ("GET", "/InspectionTypes/{id}"),
            ("POST", "/InspectionTypes"),
            ("DELETE", "/InspectionTypes"),
            ("DELETE", "/InspectionTypes/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="Jobs",
        client_attr="jobs",
        model_name="Job",
        fields=("JobID", "Name", "ShortName", "Description"),
        endpoints=(
            ("GET", "/Jobs"),
            ("GET", "/Jobs/{id}"),
            ("POST", "/Jobs"),
            ("DELETE", "/Jobs"),
            ("DELETE", "/Jobs/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="JobTypes",
        client_attr="job_types",
        model_name="JobType",
        fields=("JobTypeID", "Name", "Description"),
        endpoints=(
            ("GET", "/JobTypes"),
            ("GET", "/JobTypes/{id}"),
            ("POST", "/JobTypes"),
            ("DELETE", "/JobTypes"),
            ("DELETE", "/JobTypes/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="MaintenanceSchedulingServiceManagerCategories",
        client_attr="maintenance_scheduling_service_manager_categories",
        model_name="MaintenanceSchedulingServiceManagerCategory",
        fields=("MaintenanceSchedulingServiceManagerCategoryID", "ServiceManagerCategoryID", "MetaTag"),
        endpoints=(
            ("GET", "/MaintenanceSchedulingServiceManagerCategories"),
            ("GET", "/MaintenanceSchedulingServiceManagerCategories/{id}"),
            ("POST", "/MaintenanceSchedulingServiceManagerCategories"),
            ("DELETE", "/MaintenanceSchedulingServiceManagerCategories"),
            ("DELETE", "/MaintenanceSchedulingServiceManagerCategories/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="MaintenanceTechs",
        client_attr="maintenance_techs",
        model_name="MaintenanceTech",
        fields=(
            "MaintenanceTechID",
            "UserID",
            "IsOnDuty",
            "IsScheduleOverride",
            "ScheduleOverrideDate",
            "IsScheduleEnabled",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/MaintenanceTechs"),
            ("GET", "/MaintenanceTechs/{id}"),
            ("POST", "/MaintenanceTechs"),
            ("DELETE", "/MaintenanceTechs"),
            ("DELETE", "/MaintenanceTechs/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="MakeReadyActions",
        client_attr="make_ready_actions",
        model_name="MakeReadyAction",
        fields=("MakeReadyActionID", "Name"),
        endpoints=(
            ("GET", "/MakeReadyActions"),
            ("GET", "/MakeReadyActions/{id}"),
            ("POST", "/MakeReadyActions"),
            ("DELETE", "/MakeReadyActions"),
            ("DELETE", "/MakeReadyActions/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="MakeReadyPosts",
        client_attr="make_ready_posts",
        model_name="MakeReadyPost",
        fields=(
            "MakeReadyPostID",
            "UnitID",
            "LeaseID",
            "IsEnforceSequence",
            "StartDate",
            "CompletionDate",
            "CompletionUnitStatusTypeID",
            "IsMaintainCurrentStatus",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "Comments",
            "ManagerUserID",
            "JobID",
            "IsHighPriority",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/MakeReadyPosts"),
            ("GET", "/MakeReadyPosts/{id}"),
            ("POST", "/MakeReadyPosts"),
            ("DELETE", "/MakeReadyPosts"),
            ("DELETE", "/MakeReadyPosts/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="MakeReadyTemplateItems",
        client_attr="make_ready_template_items",
        model_name="MakeReadyTemplateItem",
        fields=(
            "MakeReadyTemplateItemID",
            "MakeReadyTemplateID",
            "MakeReadyActionID",
            "ServiceManagerIssueName",
            "Description",
            "VendorID",
            "ServiceManagerCategoryID",
            "ServiceManagerPriorityID",
            "ServiceManagerStatusID",
            "IsAssignedToPropertyDefaultUser",
            "AssignedToUserID",
            "InspectionTemplateID",
            "InspectorUserID",
            "InspectionTypeID",
            "InspectionStatusID",
            "IsNotifyWhenReady",
            "InspectionIssuesActionID",
            "ExpirationDateOffset",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "DueDateOffset",
            "ScheduledDateOffset",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/MakeReadyTemplateItems"),
            ("GET", "/MakeReadyTemplateItems/{id}"),
            ("POST", "/MakeReadyTemplateItems"),
            ("DELETE", "/MakeReadyTemplateItems"),
            ("DELETE", "/MakeReadyTemplateItems/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="MakeReadyTemplates",
        client_attr="make_ready_templates",
        model_name="MakeReadyTemplate",
        fields=("MakeReadyTemplateID", "Name", "IsActive"),
        endpoints=(
            ("GET", "/MakeReadyTemplates"),
            ("GET", "/MakeReadyTemplates/{id}"),
            ("POST", "/MakeReadyTemplates"),
            ("DELETE", "/MakeReadyTemplates"),
            ("DELETE", "/MakeReadyTemplates/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ScheduledRequests",
        client_attr="scheduled_requests",
        model_name="ScheduledRequest",
        fields=("RequestToken", "LocationID", "Action", "MetaTag"),
        endpoints=(("GET", "/ScheduledRequests"), ("GET", "/ScheduledRequests/{id}")),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerIssueLayoutLinkedFields",
        client_attr="service_manager_issue_layout_linked_fields",
        model_name="ServiceManagerIssueLayoutLinkedField",
        fields=(
            "ServiceManagerIssueLayoutLinkedFieldID",
            "ServiceManagerIssueLayoutID",
            "UserDefinedFieldID",
            "PhoneNumberTypeID",
            "Name",
            "DisplayName",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerIssueLayoutLinkedFields"),
            ("GET", "/ServiceManagerIssueLayoutLinkedFields/{id}"),
            ("POST", "/ServiceManagerIssueLayoutLinkedFields"),
            ("DELETE", "/ServiceManagerIssueLayoutLinkedFields"),
            ("DELETE", "/ServiceManagerIssueLayoutLinkedFields/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerIssueLayouts",
        client_attr="service_manager_issue_layouts",
        model_name="ServiceManagerIssueLayout",
        fields=(
            "ServiceManagerIssueLayoutID",
            "Name",
            "InfoWidth",
            "CaptionWidth",
            "IsDefault",
            "IsSystemDefault",
            "DetailHeight",
            "DescriptionHeightRatio",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerIssueLayouts"),
            ("GET", "/ServiceManagerIssueLayouts/{id}"),
            ("POST", "/ServiceManagerIssueLayouts"),
            ("DELETE", "/ServiceManagerIssueLayouts"),
            ("DELETE", "/ServiceManagerIssueLayouts/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerIssueTemplates",
        client_attr="service_manager_issue_templates",
        model_name="ServiceManagerIssueTemplate",
        fields=(
            "ServiceManagerIssueTemplateID",
            "ServiceManagerProjectTemplateID",
            "Title",
            "Description",
            "CategoryID",
            "StatusID",
            "PriorityID",
            "AssignedToUserID",
            "Notes",
            "OpenDaysAfterStart",
            "DueDaysAfterOpen",
            "Hours",
            "Seconds",
            "Sequence",
            "VendorID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerIssueTemplates"),
            ("GET", "/ServiceManagerIssueTemplates/{id}"),
            ("POST", "/ServiceManagerIssueTemplates"),
            ("DELETE", "/ServiceManagerIssueTemplates"),
            ("DELETE", "/ServiceManagerIssueTemplates/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerIssueWorkOrders",
        client_attr="service_manager_issue_work_orders",
        model_name="ServiceManagerIssueWorkOrder",
        fields=(
            "ServiceManagerIssueWorkOrderID",
            "WorkOrderID",
            "ServiceManagerIssueID",
            "HasInvoiceLink",
            "InvoiceID",
            "InvoiceDetailID",
            "HasVendorBillLink",
            "VendorBillID",
            "HasOwnerBillLink",
            "OwnerBillID",
            "PayeeAccountID",
            "PropertyID",
            "UnitID",
            "JobID",
            "Description",
            "Quantity",
            "Cost",
            "Price",
            "InventoryItemID",
            "HasPurchaseOrderLink",
            "PurchaseOrderID",
            "SmartReceiptID",
            "QuickBillID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerIssueWorkOrders"),
            ("GET", "/ServiceManagerIssueWorkOrders/{id}"),
            ("POST", "/ServiceManagerIssueWorkOrders"),
            ("DELETE", "/ServiceManagerIssueWorkOrders"),
            ("DELETE", "/ServiceManagerIssueWorkOrders/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerMemorizedIssues",
        client_attr="service_manager_memorized_issues",
        model_name="ServiceManagerMemorizedIssue",
        fields=(
            "ServiceManagerMemorizedIssueID",
            "MemorizedName",
            "MemorizedDescription",
            "Title",
            "Description",
            "Resolution",
            "CategoryID",
            "StatusID",
            "PriorityID",
            "AssignedOpenDate",
            "DueDate",
            "PayeeAccountID",
            "IsRead",
            "AssignedToUserID",
            "ProjectID",
            "ProjectSequence",
            "CurrentProjectSequence",
            "IsCustomerInitiated",
            "CustomerDescription",
            "NoteText",
            "HasPets",
            "IsAllowedToEnter",
            "IsSignatureOnFile",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "SignatureFileID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerMemorizedIssues"),
            ("GET", "/ServiceManagerMemorizedIssues/{id}"),
            ("POST", "/ServiceManagerMemorizedIssues"),
            ("DELETE", "/ServiceManagerMemorizedIssues"),
            ("DELETE", "/ServiceManagerMemorizedIssues/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerProjects",
        client_attr="service_manager_projects",
        model_name="ServiceManagerProject",
        fields=("ServiceManagerProjectID", "Name"),
        endpoints=(
            ("GET", "/ServiceManagerProjects"),
            ("GET", "/ServiceManagerProjects/{id}"),
            ("POST", "/ServiceManagerProjects"),
            ("DELETE", "/ServiceManagerProjects"),
            ("DELETE", "/ServiceManagerProjects/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerProjectTemplates",
        client_attr="service_manager_project_templates",
        model_name="ServiceManagerProjectTemplate",
        fields=(
            "ServiceManagerProjectTemplateID",
            "Name",
            "Description",
            "CategoryID",
            "StatusID",
            "PriorityID",
            "IsEnforceSequence",
            "VendorID",
            "AssignedToUserID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerProjectTemplates"),
            ("GET", "/ServiceManagerProjectTemplates/{id}"),
            ("POST", "/ServiceManagerProjectTemplates"),
            ("DELETE", "/ServiceManagerProjectTemplates"),
            ("DELETE", "/ServiceManagerProjectTemplates/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerRecurringIssues",
        client_attr="service_manager_recurring_issues",
        model_name="ServiceManagerRecurringIssue",
        fields=("ServiceManagerRecurringIssueID", "Title"),
        endpoints=(
            ("GET", "/ServiceManagerRecurringIssues"),
            ("GET", "/ServiceManagerRecurringIssues/{id}"),
            ("POST", "/ServiceManagerRecurringIssues"),
            ("DELETE", "/ServiceManagerRecurringIssues"),
            ("DELETE", "/ServiceManagerRecurringIssues/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerSavedLists",
        client_attr="service_manager_saved_lists",
        model_name="ServiceManagerSavedList",
        fields=(
            "ServiceManagerSavedListID",
            "Name",
            "OnStart",
            "SortOrder",
            "Notify",
            "RefreshMinutes",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "CreateWebUserID",
            "IsCustomerInitiated",
            "IncludeOpenIssues",
            "OwnerIDs",
            "PropertyIDs",
            "LinkedEntityType",
            "FilterID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerSavedLists"),
            ("GET", "/ServiceManagerSavedLists/{id}"),
            ("POST", "/ServiceManagerSavedLists"),
            ("DELETE", "/ServiceManagerSavedLists"),
            ("DELETE", "/ServiceManagerSavedLists/{id}"),
        ),
    ),
    MaintenanceAssetsInspectionsServiceResourceSpec(
        path="ServiceManagerTechTimes",
        client_attr="service_manager_tech_times",
        model_name="ServiceManagerTechTime",
        fields=(
            "ServiceManagerTechTimeID",
            "ServiceManagerIssueID",
            "TechUserID",
            "CheckInTime",
            "CheckInLongitude",
            "CheckInLatitude",
            "CheckOutTime",
            "CheckOutLongitude",
            "CheckOutLatitude",
            "CheckInToIssueDistance",
            "CheckOutToIssueDistance",
            "Hours",
            "Comment",
            "CreateUserID",
            "CreateDate",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "UserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ServiceManagerTechTimes"),
            ("GET", "/ServiceManagerTechTimes/{id}"),
            ("POST", "/ServiceManagerTechTimes"),
            ("DELETE", "/ServiceManagerTechTimes"),
            ("DELETE", "/ServiceManagerTechTimes/{id}"),
        ),
    ),
)

MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_MODEL_NAMES = tuple(
    dict.fromkeys(spec.model_name for spec in MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_RESOURCE_SPECS)
)
MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_RESOURCE_CLASS_NAMES = tuple(
    spec.resource_class_name for spec in MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_RESOURCE_SPECS
)

__all__ = [
    "MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_MODEL_NAMES",
    "MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_RESOURCE_CLASS_NAMES",
    "MAINTENANCE_ASSETS_INSPECTIONS_SERVICE_RESOURCE_SPECS",
    "MaintenanceAssetsInspectionsServiceEndpoint",
    "MaintenanceAssetsInspectionsServiceMethod",
    "MaintenanceAssetsInspectionsServiceResourceSpec",
]
