from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


PropertiesOwnersAssociationsViolationsMethod = Literal["GET", "POST", "DELETE"]
PropertiesOwnersAssociationsViolationsEndpoint = tuple[PropertiesOwnersAssociationsViolationsMethod, str]


@dataclass(frozen=True, slots=True)
class PropertiesOwnersAssociationsViolationsResourceSpec:
    path: str
    client_attr: str
    model_name: str
    fields: tuple[str, ...]
    endpoints: tuple[PropertiesOwnersAssociationsViolationsEndpoint, ...]

    @property
    def resource_class_name(self) -> str:
        return f"{self.path}Resource"


PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_RESOURCE_SPECS = (
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ArchitecturalRequestFiles",
        client_attr="architectural_request_files",
        model_name="ArchitecturalRequestFile",
        fields=(
            "ArchitecturalRequestFileID",
            "PropertyID",
            "FileID",
            "CreateUserID",
            "UpdateUserID",
            "Name",
            "Description",
            "CreateDate",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ArchitecturalRequestFiles"),
            ("GET", "/ArchitecturalRequestFiles/{id}"),
            ("POST", "/ArchitecturalRequestFiles"),
            ("DELETE", "/ArchitecturalRequestFiles"),
            ("DELETE", "/ArchitecturalRequestFiles/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ArchitecturalRequestForms",
        client_attr="architectural_request_forms",
        model_name="ArchitecturalRequestForm",
        fields=(
            "ArchitecturalRequestFormID",
            "Name",
            "DisplayName",
            "Description",
            "IsSystem",
            "IsReadOnly",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ArchitecturalRequestForms"),
            ("GET", "/ArchitecturalRequestForms/{id}"),
            ("POST", "/ArchitecturalRequestForms"),
            ("DELETE", "/ArchitecturalRequestForms"),
            ("DELETE", "/ArchitecturalRequestForms/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ArchitecturalRequestFormsActiveProperties",
        client_attr="architectural_request_forms_active_properties",
        model_name="ArchitecturalRequestFormsActiveProperty",
        fields=(
            "ArchitecturalRequestFormsActivePropertyID",
            "ArchitecturalRequestFormID",
            "PropertyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ArchitecturalRequestFormsActiveProperties"),
            ("GET", "/ArchitecturalRequestFormsActiveProperties/{id}"),
            ("POST", "/ArchitecturalRequestFormsActiveProperties"),
            ("DELETE", "/ArchitecturalRequestFormsActiveProperties"),
            ("DELETE", "/ArchitecturalRequestFormsActiveProperties/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ArchitecturalRequests",
        client_attr="architectural_requests",
        model_name="ArchitecturalRequest",
        fields=(
            "ArchitecturalRequestID",
            "PropertyID",
            "TenantID",
            "ArchitecturalRequestFormID",
            "CreateWebUserID",
            "CreateUserID",
            "UpdateUserID",
            "Request",
            "Description",
            "StatusComments",
            "HasBeenInBoardReview",
            "CreateDate",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ArchitecturalRequests"),
            ("GET", "/ArchitecturalRequests/{id}"),
            ("POST", "/ArchitecturalRequests"),
            ("DELETE", "/ArchitecturalRequests"),
            ("DELETE", "/ArchitecturalRequests/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="AreaItems",
        client_attr="area_items",
        model_name="AreaItem",
        fields=(
            "AreaItemID",
            "Name",
            "IsManagementOnly",
            "InspectorHelpText",
            "TenantHelpText",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/AreaItems"),
            ("GET", "/AreaItems/{id}"),
            ("POST", "/AreaItems"),
            ("DELETE", "/AreaItems"),
            ("DELETE", "/AreaItems/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="AreaItemStatuss",
        client_attr="area_item_statuses",
        model_name="AreaItemStatus",
        fields=(
            "AreaItemStatusID",
            "Name",
            "IsActionItem",
            "IsSevere",
            "IsReviewNeeded",
            "IsDefault",
            "SortOrder",
            "IsManagementOnly",
            "IsNoteRequired",
            "IsImageRequired",
            "CreateDate",
            "CreateUserID",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/AreaItemStatuss"),
            ("GET", "/AreaItemStatuss/{id}"),
            ("POST", "/AreaItemStatuss"),
            ("DELETE", "/AreaItemStatuss"),
            ("DELETE", "/AreaItemStatuss/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="AreaPredefinedItems",
        client_attr="area_predefined_items",
        model_name="AreaPredefinedItem",
        fields=(
            "AreaPredefinedItemID",
            "AreaID",
            "Name",
            "IsManagementOnly",
            "InspectorHelpText",
            "TenantHelpText",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/AreaPredefinedItems"),
            ("GET", "/AreaPredefinedItems/{id}"),
            ("POST", "/AreaPredefinedItems"),
            ("DELETE", "/AreaPredefinedItems"),
            ("DELETE", "/AreaPredefinedItems/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="Areas",
        client_attr="areas",
        model_name="Area",
        fields=(
            "AreaID",
            "Name",
            "IsManagementOnly",
            "InspectorHelpText",
            "TenantHelpText",
            "CreateUserID",
            "UpdateUserID",
            "CreateDate",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Areas"),
            ("GET", "/Areas/{id}"),
            ("POST", "/Areas"),
            ("DELETE", "/Areas"),
            ("DELETE", "/Areas/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="AssociationSettings",
        client_attr="association_settings",
        model_name="AssociationSetting",
        fields=(
            "AssociationSettingsID",
            "PropertyID",
            "ArchitecturalRequestsTWAMessageRTF",
            "ArchitecturalRequestsTWAMessageHTML",
            "ArchitecturalRequestsTWASubmitMessageRTF",
            "ArchitecturalRequestsTWASubmitMessageHTML",
            "ArchitecturalRequestsTWAReviewMessageRTF",
            "ArchitecturalRequestsTWAReviewMessageHTML",
            "IsArchitecturalRequestsAttachmentRequired",
            "CanBoardViewArchitecturalRequestsOnTWA",
            "CanBoardVoteArchitecturalRequestsOnTWA",
            "IsDoNotDisplayArchitecturalRequestsOnTWAUntilInBoardReview",
            "CreateUserID",
            "UpdateUserID",
            "CreateDate",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/AssociationSettings"),
            ("GET", "/AssociationSettings/{id}"),
            ("POST", "/AssociationSettings"),
            ("DELETE", "/AssociationSettings"),
            ("DELETE", "/AssociationSettings/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="BirdsEyeViewColors",
        client_attr="birds_eye_view_colors",
        model_name="BirdsEyeViewColor",
        fields=(
            "Name",
            "HexValue",
        ),
        endpoints=(
            ("GET", "/BirdsEyeViewColors"),
            ("GET", "/BirdsEyeViewColors/{id}"),
            ("POST", "/BirdsEyeViewColors"),
            ("DELETE", "/BirdsEyeViewColors"),
            ("DELETE", "/BirdsEyeViewColors/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="BirdsEyeViewMapOverlays",
        client_attr="birds_eye_view_map_overlays",
        model_name="BirdsEyeViewMapOverlay",
        fields=(
            "BirdsEyeViewMapOverlayID",
            "BirdsEyeViewMapID",
            "BirdsEyeViewOverlayID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/BirdsEyeViewMapOverlays"),
            ("GET", "/BirdsEyeViewMapOverlays/{id}"),
            ("POST", "/BirdsEyeViewMapOverlays"),
            ("DELETE", "/BirdsEyeViewMapOverlays"),
            ("DELETE", "/BirdsEyeViewMapOverlays/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="BirdsEyeViewMaps",
        client_attr="birds_eye_view_maps",
        model_name="BirdsEyeViewMap",
        fields=(
            "BirdsEyeViewMapID",
            "Name",
            "Description",
            "BackgroundImageID",
            "BackgroundWidth",
            "BackgroundHeight",
            "OverlayTextScript",
            "OverlayTextFontFamily",
            "OverlayTextFontSize",
            "OverlayTextFontIsBold",
            "OverlayTextFontIsItalic",
            "OverlayTextFontIsUnderlined",
            "OverlayTextFontIsStrikeThru",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/BirdsEyeViewMaps"),
            ("GET", "/BirdsEyeViewMaps/{id}"),
            ("POST", "/BirdsEyeViewMaps"),
            ("DELETE", "/BirdsEyeViewMaps"),
            ("DELETE", "/BirdsEyeViewMaps/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="BirdsEyeViewMapSettings",
        client_attr="birds_eye_view_map_settings",
        model_name="BirdsEyeViewMapSetting",
        fields=(
            "BirdsEyeViewMapSettingID",
            "BirdsEyeViewMapID",
            "IsActive",
            "ShapeTransparency",
            "ShapeFillColorHex",
            "DefaultBirdsEyeViewOverlayID",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/BirdsEyeViewMapSettings"),
            ("GET", "/BirdsEyeViewMapSettings/{id}"),
            ("POST", "/BirdsEyeViewMapSettings"),
            ("DELETE", "/BirdsEyeViewMapSettings"),
            ("DELETE", "/BirdsEyeViewMapSettings/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="BirdsEyeViewOverlays",
        client_attr="birds_eye_view_overlays",
        model_name="BirdsEyeViewOverlay",
        fields=(
            "BirdsEyeViewOverlayID",
            "IsActive",
            "Name",
            "Description",
            "IsShowAsOfDate",
            "IsShowToDate",
            "IsShowFloorsFilter",
            "IsShowPropertyFilter",
            "IsOverrideHoverScript",
            "FormulaToEvaluate",
            "DisplayText",
            "SubHeadingText",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "OverlayType",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/BirdsEyeViewOverlays"),
            ("GET", "/BirdsEyeViewOverlays/{id}"),
            ("POST", "/BirdsEyeViewOverlays"),
            ("DELETE", "/BirdsEyeViewOverlays"),
            ("DELETE", "/BirdsEyeViewOverlays/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="CodeStageColors",
        client_attr="code_stage_colors",
        model_name="CodeStageColor",
        fields=(
            "CodeStageColorID",
            "StageNumber",
            "ColorHexValue",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/CodeStageColors"),
            ("GET", "/CodeStageColors/{id}"),
            ("POST", "/CodeStageColors"),
            ("DELETE", "/CodeStageColors"),
            ("DELETE", "/CodeStageColors/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="Colors",
        client_attr="colors",
        model_name="Color",
        fields=(
            "ColorID",
            "Name",
            "HexValue",
        ),
        endpoints=(
            ("GET", "/Colors"),
            ("GET", "/Colors/{id}"),
            ("POST", "/Colors"),
            ("DELETE", "/Colors"),
            ("DELETE", "/Colors/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="Committees",
        client_attr="committees",
        model_name="Committee",
        fields=(
            "CommitteeID",
            "Name",
            "DisplayName",
            "Description",
            "IsActive",
            "CanViewArchitecturalRequestsOnTWA",
            "CanVoteArchitecturalRequestsOnTWA",
            "CreateDate",
            "UpdateDate",
            "CreateUserID",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Committees"),
            ("GET", "/Committees/{id}"),
            ("POST", "/Committees"),
            ("DELETE", "/Committees"),
            ("DELETE", "/Committees/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="CommunityEvents",
        client_attr="community_events",
        model_name="CommunityEvent",
        fields=(
            "CommunityEventID",
            "ParentCommunityEventID",
            "PropertyID",
            "StartDate",
            "EndDate",
            "Subject",
            "Description",
            "Location",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "IsRecurring",
            "ColorID",
            "CommunityEventRecurrencePatternOfRecurrence",
            "CommunityEventRecurrenceFromDate",
            "CommunityEventRecurrenceToDate",
            "CommunityEventRecurrenceValue1",
            "CommunityEventRecurrenceValue2",
            "CommunityEventRecurrenceDatePostedThru",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/CommunityEvents"),
            ("GET", "/CommunityEvents/{id}"),
            ("POST", "/CommunityEvents"),
            ("DELETE", "/CommunityEvents"),
            ("DELETE", "/CommunityEvents/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="CommunityEventTypes",
        client_attr="community_event_types",
        model_name="CommunityEventType",
        fields=(
            "CommunityEventTypeID",
            "Name",
            "Description",
            "IsActive",
            "Color",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/CommunityEventTypes"),
            ("GET", "/CommunityEventTypes/{id}"),
            ("POST", "/CommunityEventTypes"),
            ("DELETE", "/CommunityEventTypes"),
            ("DELETE", "/CommunityEventTypes/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="HomeOwnerStatuss",
        client_attr="home_owner_statuses",
        model_name="HomeOwnerStatus",
        fields=(
            "HomeOwnerStatusID",
            "Name",
            "Description",
            "IsCommunityOwned",
            "IsRVStatus",
            "SortOrder",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HomeOwnerStatuss"),
            ("GET", "/HomeOwnerStatuss/{id}"),
            ("POST", "/HomeOwnerStatuss"),
            ("DELETE", "/HomeOwnerStatuss"),
            ("DELETE", "/HomeOwnerStatuss/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="HomeOwnerStatusHistories",
        client_attr="home_owner_status_histories",
        model_name="HomeOwnerStatusHistory",
        fields=(
            "HomeownerStatusHistoryID",
            "AssetID",
            "HomeOwnerStatusID",
            "StartDate",
            "EndDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HomeOwnerStatusHistories"),
            ("GET", "/HomeOwnerStatusHistories/{id}"),
            ("POST", "/HomeOwnerStatusHistories"),
            ("DELETE", "/HomeOwnerStatusHistories"),
            ("DELETE", "/HomeOwnerStatusHistories/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerCheckSetups",
        client_attr="owner_check_setups",
        model_name="OwnerCheckSetup",
        fields=(
            "OwnerCheckSetupID",
            "Name",
        ),
        endpoints=(
            ("GET", "/OwnerCheckSetups"),
            ("GET", "/OwnerCheckSetups/{id}"),
            ("POST", "/OwnerCheckSetups"),
            ("DELETE", "/OwnerCheckSetups"),
            ("DELETE", "/OwnerCheckSetups/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerGroupFilters",
        client_attr="owner_group_filters",
        model_name="OwnerGroupFilter",
        fields=(
            "FilterID",
            "Name",
            "Description",
            "TargetID",
            "SubTargetID",
            "IsSystem",
            "IsAdvanced",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "UserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/OwnerGroupFilters"),
            ("GET", "/OwnerGroupFilters/{id}"),
            ("POST", "/OwnerGroupFilters"),
            ("DELETE", "/OwnerGroupFilters"),
            ("DELETE", "/OwnerGroupFilters/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerGroups",
        client_attr="owner_groups",
        model_name="OwnerGroup",
        fields=(
            "GroupID",
            "OwnerGroupID",
            "Name",
        ),
        endpoints=(
            ("GET", "/OwnerGroups"),
            ("GET", "/OwnerGroups/{id}"),
            ("POST", "/OwnerGroups"),
            ("DELETE", "/OwnerGroups"),
            ("DELETE", "/OwnerGroups/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerProspectLeadSources",
        client_attr="owner_prospect_lead_sources",
        model_name="OwnerProspectLeadSource",
        fields=(
            "OwnerProspectLeadSourceID",
            "Description",
        ),
        endpoints=(
            ("GET", "/OwnerProspectLeadSources"),
            ("GET", "/OwnerProspectLeadSources/{id}"),
            ("POST", "/OwnerProspectLeadSources"),
            ("DELETE", "/OwnerProspectLeadSources"),
            ("DELETE", "/OwnerProspectLeadSources/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerProspects",
        client_attr="owner_prospects",
        model_name="OwnerProspect",
        fields=(
            "OwnerProspectID",
            "Name",
            "DisplayName",
        ),
        endpoints=(
            ("GET", "/OwnerProspects"),
            ("GET", "/OwnerProspects/{id}"),
            ("POST", "/OwnerProspects"),
            ("DELETE", "/OwnerProspects"),
            ("DELETE", "/OwnerProspects/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnershipTransferPostings",
        client_attr="ownership_transfer_postings",
        model_name="OwnershipTransferPosting",
        fields=(
            "OwnershipTransferPostingID",
            "PostingDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/OwnershipTransferPostings"),
            ("GET", "/OwnershipTransferPostings/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerWebAccessOwnerPreferences",
        client_attr="owner_web_access_owner_preferences",
        model_name="OwnerWebAccessOwnerPreference",
        fields=(
            "OwnerWebAccessOwnerPreferenceID",
            "OwnerID",
            "Message",
            "OverrideDefaults",
            "ShowReports",
            "AllowContributions",
            "ShowChecks",
            "ShowFees",
            "ShowOwnerships",
            "ShowOpenIssues",
            "ShowClosedIssues",
            "ShowWorkOrders",
            "ShowSecurityDepositsHeld",
            "ShowBalance",
            "ShowOwnershipPercentage",
            "ShowReserve",
            "ShowOwnerChecks",
            "ShowBills",
            "ShowBillAttachments",
            "ShowPassthruFees",
            "ExcludeVendorInformationFromServiceIssues",
            "ExcludeTenantInformationFromServiceIssues",
            "AllowNotes",
            "ShowOpenEstimates",
            "ShowClosedEstimates",
            "ShowInspectionReports",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/OwnerWebAccessOwnerPreferences"),
            ("GET", "/OwnerWebAccessOwnerPreferences/{id}"),
            ("POST", "/OwnerWebAccessOwnerPreferences"),
            ("DELETE", "/OwnerWebAccessOwnerPreferences"),
            ("DELETE", "/OwnerWebAccessOwnerPreferences/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="OwnerWebAccessReportPrivileges",
        client_attr="owner_web_access_report_privileges",
        model_name="OwnerWebAccessReportPrivilege",
        fields=(
            "OwnerWebAccessReportPrivilegeModelID",
            "OwnerID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/OwnerWebAccessReportPrivileges"),
            ("GET", "/OwnerWebAccessReportPrivileges/{id}"),
            ("POST", "/OwnerWebAccessReportPrivileges"),
            ("DELETE", "/OwnerWebAccessReportPrivileges"),
            ("DELETE", "/OwnerWebAccessReportPrivileges/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="PropertyGroupFilter",
        client_attr="property_group_filter",
        model_name="PropertyGroupFilter",
        fields=(
            "FilterID",
            "Name",
            "Description",
            "TargetID",
            "SubTargetID",
            "IsSystem",
            "IsAdvanced",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "UserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/PropertyGroupFilter"),
            ("GET", "/PropertyGroupFilter/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="PropertyGroupFilters",
        client_attr="property_group_filters",
        model_name="PropertyGroupFilter",
        fields=(
            "FilterID",
            "Name",
            "Description",
            "TargetID",
            "SubTargetID",
            "IsSystem",
            "IsAdvanced",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "UserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/PropertyGroupFilters"),
            ("GET", "/PropertyGroupFilters/{id}"),
            ("POST", "/PropertyGroupFilters"),
            ("DELETE", "/PropertyGroupFilters"),
            ("DELETE", "/PropertyGroupFilters/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="PropertyManagementFeeSetup",
        client_attr="property_management_fee_setup",
        model_name="PropertyManagementFeeSetup",
        fields=(
            "PropertyManagementFeeSetupID",
            "PropertyID",
            "ManagementFeeSetupID",
            "ActiveStartDate",
            "ActiveEndDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/PropertyManagementFeeSetup"),
            ("GET", "/PropertyManagementFeeSetup/{id}"),
            ("POST", "/PropertyManagementFeeSetup"),
            ("DELETE", "/PropertyManagementFeeSetup"),
            ("DELETE", "/PropertyManagementFeeSetup/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="PropertyManagementFeeSetups",
        client_attr="property_management_fee_setups",
        model_name="PropertyManagementFeeSetup",
        fields=(
            "PropertyManagementFeeSetupID",
            "PropertyID",
            "ManagementFeeSetupID",
            "ActiveStartDate",
            "ActiveEndDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/PropertyManagementFeeSetups"),
            ("GET", "/PropertyManagementFeeSetups/{id}"),
            ("POST", "/PropertyManagementFeeSetups"),
            ("DELETE", "/PropertyManagementFeeSetups"),
            ("DELETE", "/PropertyManagementFeeSetups/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="SiteClassifications",
        client_attr="site_classifications",
        model_name="SiteClassification",
        fields=(
            "SiteClassificationID",
            "Name",
            "Description",
            "ShortName",
            "SortOrder",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/SiteClassifications"),
            ("GET", "/SiteClassifications/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="SiteGroups",
        client_attr="site_groups",
        model_name="SiteGroup",
        fields=(
            "SiteGroupID",
            "PropertyID",
            "CreateUserID",
            "UpdateUserID",
            "ConcurrencyID",
            "Name",
            "MarketingName",
            "MarketingDescription",
            "CreateDate",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/SiteGroups"),
            ("GET", "/SiteGroups/{id}"),
            ("POST", "/SiteGroups"),
            ("DELETE", "/SiteGroups"),
            ("DELETE", "/SiteGroups/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="SiteTypes",
        client_attr="site_types",
        model_name="SiteType",
        fields=(
            "SiteTypeID",
            "Name",
            "IsEquipmentTypeNotRequired",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/SiteTypes"),
            ("GET", "/SiteTypes/{id}"),
            ("POST", "/SiteTypes"),
            ("DELETE", "/SiteTypes"),
            ("DELETE", "/SiteTypes/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ViolationCategories",
        client_attr="violation_categories",
        model_name="ViolationCategory",
        fields=(
            "ViolationCategoryID",
            "Name",
            "Description",
            "IsActive",
        ),
        endpoints=(
            ("GET", "/ViolationCategories"),
            ("GET", "/ViolationCategories/{id}"),
            ("POST", "/ViolationCategories"),
            ("DELETE", "/ViolationCategories"),
            ("DELETE", "/ViolationCategories/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ViolationCodeGroups",
        client_attr="violation_code_groups",
        model_name="ViolationCodeGroup",
        fields=(
            "ViolationCodeGroupID",
            "Name",
            "LetterTemplateID",
            "ChargeTypeID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ViolationCodeGroups"),
            ("GET", "/ViolationCodeGroups/{id}"),
            ("POST", "/ViolationCodeGroups"),
            ("DELETE", "/ViolationCodeGroups"),
            ("DELETE", "/ViolationCodeGroups/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="ViolationCodes",
        client_attr="violation_codes",
        model_name="ViolationCode",
        fields=(
            "ViolationCodeID",
            "ViolationCodeGroupID",
            "Code",
            "ViolationCategoryID",
            "Description",
            "ResolveAction",
            "CCRReference",
            "InternalNotes",
            "IsOverrideViolationCodeGroupStages",
            "LetterTemplateID",
            "ChargeTypeID",
            "IsActive",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ViolationCodes"),
            ("GET", "/ViolationCodes/{id}"),
        ),
    ),
    PropertiesOwnersAssociationsViolationsResourceSpec(
        path="Violations",
        client_attr="violations",
        model_name="Violation",
        fields=(
            "ViolationID",
            "PropertyID",
            "ImageID",
            "TenantID",
            "UnitID",
            "ViolationCodeID",
            "ViolationCategoryID",
            "ViolationDate",
            "Description",
            "ResolveAction",
            "CCRReference",
            "InternalNotes",
            "IsClosed",
            "CloseDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Violations"),
            ("GET", "/Violations/{id}"),
            ("POST", "/Violations"),
            ("DELETE", "/Violations"),
            ("DELETE", "/Violations/{id}"),
        ),
    ),
)

PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_MODEL_NAMES = tuple(
    dict.fromkeys(spec.model_name for spec in PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_RESOURCE_SPECS)
)
PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_RESOURCE_CLASS_NAMES = tuple(
    spec.resource_class_name for spec in PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_RESOURCE_SPECS
)

__all__ = [
    "PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_MODEL_NAMES",
    "PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_RESOURCE_CLASS_NAMES",
    "PROPERTIES_OWNERS_ASSOCIATIONS_VIOLATIONS_RESOURCE_SPECS",
    "PropertiesOwnersAssociationsViolationsEndpoint",
    "PropertiesOwnersAssociationsViolationsMethod",
    "PropertiesOwnersAssociationsViolationsResourceSpec",
]
