from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


ReferenceMiscMethod = Literal["GET", "POST", "DELETE"]
ReferenceMiscEndpoint = tuple[ReferenceMiscMethod, str]


@dataclass(frozen=True, slots=True)
class ReferenceMiscResourceSpec:
    path: str
    client_attr: str
    model_name: str
    fields: tuple[str, ...]
    endpoints: tuple[ReferenceMiscEndpoint, ...]

    @property
    def resource_class_name(self) -> str:
        return f"{self.path}Resource"


REFERENCE_MISC_RESOURCE_SPECS = (
    ReferenceMiscResourceSpec(
        path="Appointments",
        client_attr="appointments",
        model_name="Appointment",
        fields=(
            "AppointmentID",
            "ParentAppointmentID",
            "StartDate",
            "EndDate",
            "ReminderDate",
            "Subject",
            "Description",
            "ColorID",
            "IsReminder",
            "IsCalendarIntegration",
            "IsRecurring",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "TenantID",
            "ProspectID",
            "OwnerID",
            "VendorID",
            "IssueID",
            "ServiceManagerIssueID",
            "OwnerProspectID",
            "AppointmentRecurrenceFromDate",
            "AppointmentRecurrenceToDate",
            "AppointmentRecurrenceValue1",
            "AppointmentRecurrenceValue2",
            "AppointmentRecurrenceDatePostedThru",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Appointments"),
            ("GET", "/Appointments/{id}"),
            ("POST", "/Appointments"),
            ("DELETE", "/Appointments"),
            ("DELETE", "/Appointments/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="ContactTypes",
        client_attr="contact_types",
        model_name="ContactType",
        fields=("ContactTypeID", "Name"),
        endpoints=(
            ("GET", "/ContactTypes"),
            ("GET", "/ContactTypes/{id}"),
            ("POST", "/ContactTypes"),
            ("DELETE", "/ContactTypes"),
            ("DELETE", "/ContactTypes/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="DefaultChargeSettings",
        client_attr="default_charge_settings",
        model_name="DefaultChargeSetting",
        fields=(
            "DefaultChargeSettingID",
            "PropertyID",
            "IsActive",
            "IsOneTimeCharge",
            "IsDeterminePastPosting",
            "PastPostingPostDay",
            "IsExcludeInheritedCharges",
            "IsPostZeroCharges",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/DefaultChargeSettings"),
            ("GET", "/DefaultChargeSettings/{id}"),
            ("POST", "/DefaultChargeSettings"),
            ("DELETE", "/DefaultChargeSettings"),
            ("DELETE", "/DefaultChargeSettings/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="Floorplans",
        client_attr="floorplans",
        model_name="Floorplan",
        fields=(
            "FloorplanID",
            "Name",
            "MarketingDescription",
            "PropertyID",
            "PriceLow",
            "PriceHigh",
            "UseAssociatedPricingData",
            "Bedrooms",
            "UseAssociatedBedroomData",
            "Bathrooms",
            "UseAssociatedBathroomData",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Floorplans"),
            ("GET", "/Floorplans/{id}"),
            ("POST", "/Floorplans"),
            ("DELETE", "/Floorplans"),
            ("DELETE", "/Floorplans/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="Floors",
        client_attr="floors",
        model_name="Floor",
        fields=(
            "FloorID",
            "Name",
            "SortOrder",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Floors"),
            ("GET", "/Floors/{id}"),
            ("POST", "/Floors"),
            ("DELETE", "/Floors"),
            ("DELETE", "/Floors/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="Forecasts",
        client_attr="forecasts",
        model_name="Forecast",
        fields=("ForecastID",),
        endpoints=(
            ("GET", "/Forecasts"),
            ("GET", "/Forecasts/{id}"),
            ("POST", "/Forecasts"),
            ("DELETE", "/Forecasts"),
            ("DELETE", "/Forecasts/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="GeneratedLeaseRenewals",
        client_attr="generated_lease_renewals",
        model_name="GeneratedLeaseRenewal",
        fields=(
            "GeneratedLeaseRenewalID",
            "LeaseRenewalID",
            "ParentLeaseID",
            "AssetID",
            "UnitID",
            "LeaseTermID",
            "LeaseSignDate",
            "LeaseStartDate",
            "LeaseEndDate",
            "DocumentID",
            "EmailSentItemID",
            "LetterTemplateID",
            "Comment",
            "StatusModifiedDate",
            "StatusModifiedByUserID",
            "StatusModifiedByWebUserID",
            "IsComplete",
            "CompletedDate",
            "CompletedByUserID",
            "CompletedByWebUserID",
            "ExpirationDate",
            "HasLandlordSignature",
            "RecipientMessage",
            "BlueMoonSignableDocumentID",
            "SignablePDFTemplateID",
            "DocumentPacketID",
            "CreateUserID",
            "UpdateUserID",
            "CreateDate",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/GeneratedLeaseRenewals"),
            ("GET", "/GeneratedLeaseRenewals/{id}"),
            ("POST", "/GeneratedLeaseRenewals"),
            ("DELETE", "/GeneratedLeaseRenewals"),
            ("DELETE", "/GeneratedLeaseRenewals/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="GPRAutomationSchedules",
        client_attr="gpr_automation_schedules",
        model_name="GPRAutomationSchedule",
        fields=(
            "GPRAutomationScheduleID",
            "PropertyGroupID",
            "Name",
            "PostingDay",
            "RunDay",
            "NotificationEmail",
            "JournalComment",
            "IncludeDetails",
            "IsActive",
            "StartDate",
            "EndDate",
            "MarketRentDate",
            "LastRunDate",
            "NextRunDate",
            "GLAccountRentalIncomeID",
            "GLAccountMarketRentID",
            "GLAccountVacancyLossID",
            "GLAccountLossToLeaseID",
            "GLAccountBeginningPrepayID",
            "GLAccountEndingPrepayID",
            "GLAccountBeginningArrearsID",
            "GLAccountEndingArrearsID",
            "GLAccountAdjustmentID",
            "CreateUserID",
            "UpdateUserID",
            "CreateDate",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/GPRAutomationSchedules"),
            ("GET", "/GPRAutomationSchedules/{id}"),
            ("POST", "/GPRAutomationSchedules"),
            ("DELETE", "/GPRAutomationSchedules"),
            ("DELETE", "/GPRAutomationSchedules/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="GPRPostingConfigs",
        client_attr="gpr_posting_configs",
        model_name="GPRPostingConfig",
        fields=(
            "GPRPostingConfigID",
            "Name",
            "IsDefault",
            "GLAccountMarketRentID",
            "GLAccountVacancyLossID",
            "GLAccountLossToLeaseID",
            "GLAccountBeginningPrepayID",
            "GLAccountEndingPrepayID",
            "GLAccountBeginningArrearsID",
            "GLAccountEndingArrearsID",
            "GLAccountAdjustmentID",
            "IsArchived",
            "GPRAutomationScheduleID",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/GPRPostingConfigs"),
            ("GET", "/GPRPostingConfigs/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="GPRPostingHistory",
        client_attr="gpr_posting_history",
        model_name="GPRPostingHistory",
        fields=(
            "GPRPostingHistoryID",
            "FromDate",
            "ToDate",
            "PostDate",
            "MarketRentDate",
            "CashJournalID",
            "AccrualJournalID",
            "Comment",
            "GLAccountRentalIncomeID",
            "GLAccountMarketRentID",
            "GLAccountVacancyLossID",
            "GLAccountLossToLeaseID",
            "GLAccountBeginningPrepayID",
            "GLAccountEndingPrepayID",
            "GLAccountBeginningArrearsID",
            "GLAccountEndingArrearsID",
            "GLAccountAdjustmentID",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "IsDeleted",
            "DeleteUserID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/GPRPostingHistory"),
            ("GET", "/GPRPostingHistory/{id}"),
            ("POST", "/GPRPostingHistory"),
            ("DELETE", "/GPRPostingHistory"),
            ("DELETE", "/GPRPostingHistory/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="GuestCardTemplates",
        client_attr="guest_card_templates",
        model_name="GuestCardTemplate",
        fields=("GuestCardTemplateID", "Name", "ConcurrencyID"),
        endpoints=(
            ("GET", "/GuestCardTemplates"),
            ("GET", "/GuestCardTemplates/{id}"),
            ("POST", "/GuestCardTemplates"),
            ("DELETE", "/GuestCardTemplates"),
            ("DELETE", "/GuestCardTemplates/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="History",
        client_attr="history",
        model_name="History",
        fields=(
            "HistoryTypeString",
            "HistoryID",
            "ParentID",
            "HistoryCategoryID",
            "HistoryDate",
            "HistoryEndDate",
            "EntityName",
            "Note",
            "Result",
            "FileID",
            "IsReadOnly",
            "IsLocked",
            "IsCompleted",
            "IsContactMade",
            "IsFirstContact",
            "IsConversion",
            "IsReturn",
            "IsPinned",
            "IsPOComment",
            "IsOwnerStatement",
            "IsShowOnOwnerStatement",
            "HasAttachment",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "Hours",
            "ServiceManagerCategoryID",
            "ViolationCategoryID",
            "HistoryAttachments",
            "AccountStatementURL",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/History"),
            ("GET", "/History/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryCalls",
        client_attr="history_calls",
        model_name="HistoryCall",
        fields=(
            "HistoryID",
            "HistoryCategoryID",
            "HistoryDate",
            "HistoryEndDate",
            "Note",
            "Result",
            "IsFirstContact",
            "IsLocked",
            "IsCompleted",
            "IsContactMade",
            "IsPinned",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "ParentID",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HistoryCalls"),
            ("GET", "/HistoryCalls/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryCategories",
        client_attr="history_categories",
        model_name="HistoryCategory",
        fields=("HistoryCategoryID", "Name"),
        endpoints=(
            ("GET", "/HistoryCategories"),
            ("GET", "/HistoryCategories/{id}"),
            ("POST", "/HistoryCategories"),
            ("DELETE", "/HistoryCategories"),
            ("DELETE", "/HistoryCategories/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryCategory",
        client_attr="history_category",
        model_name="HistoryCategory",
        fields=("HistoryCategoryID", "Name"),
        endpoints=(
            ("GET", "/HistoryCategory"),
            ("GET", "/HistoryCategory/{id}"),
            ("POST", "/HistoryCategory"),
            ("DELETE", "/HistoryCategory"),
            ("DELETE", "/HistoryCategory/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryEmails",
        client_attr="history_emails",
        model_name="HistoryEmail",
        fields=(
            "HistoryID",
            "HistoryCategoryID",
            "HistoryDate",
            "HistoryEndDate",
            "Note",
            "Result",
            "IsFirstContact",
            "IsLocked",
            "IsCompleted",
            "IsPinned",
            "IsContactMade",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "ParentID",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HistoryEmails"),
            ("GET", "/HistoryEmails/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryNotes",
        client_attr="history_notes",
        model_name="HistoryNote",
        fields=(
            "HistoryID",
            "HistoryType",
            "HistoryCategoryID",
            "HistoryDate",
            "Note",
            "FileID",
            "IsShowInPOComments",
            "IsLocked",
            "IsPinned",
            "CreateUserID",
            "UpdateUserID",
            "ParentID",
            "CreateDate",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HistoryNotes"),
            ("GET", "/HistoryNotes/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistorySystemNotes",
        client_attr="history_system_notes",
        model_name="HistorySystemNote",
        fields=(
            "HistoryID",
            "HistoryCategoryID",
            "HistoryDate",
            "Note",
            "FileID",
            "IsShowInPOComments",
            "IsLocked",
            "IsPinned",
            "CreateUserID",
            "UpdateUserID",
            "ParentID",
            "UpdateDate",
            "CreateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HistorySystemNotes"),
            ("GET", "/HistorySystemNotes/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryViolationNotes",
        client_attr="history_violation_notes",
        model_name="HistoryViolationNote",
        fields=(
            "HistoryID",
            "HistoryCategoryID",
            "HistoryDate",
            "Note",
            "IsLocked",
            "IsPinned",
            "CreateUserID",
            "UpdateUserID",
            "ParentID",
            "UpdateDate",
            "CreateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HistoryViolationNotes"),
            ("GET", "/HistoryViolationNotes/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="HistoryVisits",
        client_attr="history_visits",
        model_name="HistoryVisit",
        fields=(
            "HistoryID",
            "HistoryCategoryID",
            "HistoryDate",
            "HistoryEndDate",
            "Note",
            "Result",
            "IsFirstContact",
            "IsLocked",
            "IsCompleted",
            "IsPinned",
            "IsContactMade",
            "CreateUserID",
            "UpdateUserID",
            "ParentID",
            "CreateDate",
            "UpdateDate",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/HistoryVisits"),
            ("GET", "/HistoryVisits/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="Holidays",
        client_attr="holidays",
        model_name="Holiday",
        fields=(
            "HolidayID",
            "PropertyID",
            "HolidayDate",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Holidays"),
            ("GET", "/Holidays/{id}"),
            ("POST", "/Holidays"),
            ("DELETE", "/Holidays"),
            ("DELETE", "/Holidays/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="IncomingTexts",
        client_attr="incoming_texts",
        model_name="IncomingText",
        fields=(
            "IncomingTextID",
            "PhoneNumber",
            "Message",
            "ReceivedDate",
            "ParentID",
            "ParentType",
            "ReadUserID",
            "ReadDate",
            "IsMMS",
            "SegmentCount",
            "LocationID",
            "ResourceSID",
            "HistoryCategoryID",
            "MainLocationIncomingTextID",
            "ReceivingPhoneNumberString",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/IncomingTexts"),
            ("GET", "/IncomingTexts/{id}"),
            ("POST", "/IncomingTexts"),
            ("DELETE", "/IncomingTexts"),
            ("DELETE", "/IncomingTexts/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="InventoryItem",
        client_attr="inventory_item",
        model_name="InventoryItem",
        fields=("InventoryItemID", "Name", "Description"),
        endpoints=(
            ("GET", "/InventoryItem"),
            ("GET", "/InventoryItem/{id}"),
            ("POST", "/InventoryItem"),
            ("DELETE", "/InventoryItem"),
            ("DELETE", "/InventoryItem/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="InventoryItems",
        client_attr="inventory_items",
        model_name="InventoryItem",
        fields=("InventoryItemID", "Name", "Description"),
        endpoints=(
            ("GET", "/InventoryItems"),
            ("GET", "/InventoryItems/{id}"),
            ("POST", "/InventoryItems"),
            ("DELETE", "/InventoryItems"),
            ("DELETE", "/InventoryItems/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="LeadSources",
        client_attr="lead_sources",
        model_name="LeadSource",
        fields=(
            "ProspectLeadSourceID",
            "Description",
            "IsActive",
            "PhoneNumber",
            "StrippedPhoneNumber",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/LeadSources"),
            ("GET", "/LeadSources/{id}"),
            ("POST", "/LeadSources"),
            ("DELETE", "/LeadSources"),
            ("DELETE", "/LeadSources/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="MarketingFields",
        client_attr="marketing_fields",
        model_name="MarketingField",
        fields=("MarketingFieldID", "IsEnabled", "MetaTag"),
        endpoints=(
            ("GET", "/MarketingFields"),
            ("GET", "/MarketingFields/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="MultiTenantMasterPayments",
        client_attr="multi_tenant_master_payments",
        model_name="MultiTenantMasterPayment",
        fields=(
            "MultiTenantMasterPaymentID",
            "CheckNumber",
            "Amount",
            "TransactionDate",
            "DepositID",
            "PaymentFrom",
            "Comment",
            "ReceiptID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/MultiTenantMasterPayments"),
            ("GET", "/MultiTenantMasterPayments/{id}"),
            ("POST", "/MultiTenantMasterPayments"),
            ("DELETE", "/MultiTenantMasterPayments"),
            ("DELETE", "/MultiTenantMasterPayments/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="MultiTenantPayments",
        client_attr="multi_tenant_payments",
        model_name="MultiTenantPayment",
        fields=(
            "MultiTenantPaymentID",
            "CheckNumber",
            "Amount",
            "TransactionDate",
            "DepositID",
            "PaymentFrom",
            "Comment",
            "ReceiptID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/MultiTenantPayments"),
            ("GET", "/MultiTenantPayments/{id}"),
            ("POST", "/MultiTenantPayments"),
            ("DELETE", "/MultiTenantPayments"),
            ("DELETE", "/MultiTenantPayments/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="OnlineListingsRegister",
        client_attr="online_listings_register",
        model_name="OnlineListingsRegister",
        fields=(
            "PropertyShortName",
            "UnitShortName",
            "UnitName",
            "UnitID",
            "PropertyID",
            "OnlineListingFieldMappings",
            "MetaTag",
        ),
        endpoints=(("GET", "/OnlineListingsRegister"),),
    ),
    ReferenceMiscResourceSpec(
        path="RecurringJournals",
        client_attr="recurring_journals",
        model_name="RecurringJournal",
        fields=(
            "RecurringJournalID",
            "IsPeriodAdjustment",
            "Reference",
            "Memo",
            "Amount",
            "StartDate",
            "EndDate",
            "LastPostDate",
            "AdjustedPostDate",
            "NextPostDate",
            "Frequency",
            "TimesLeft",
            "IsAutomated",
            "AutomationNotificationEmail",
            "CreateDate",
            "CreateUserID",
            "UpdateDate",
            "UpdateUserID",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/RecurringJournals"),
            ("GET", "/RecurringJournals/{id}"),
            ("POST", "/RecurringJournals"),
            ("DELETE", "/RecurringJournals"),
            ("DELETE", "/RecurringJournals/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="Reminders",
        client_attr="reminders",
        model_name="Reminder",
        fields=(
            "ReminderID",
            "ParentReminderID",
            "TaskType",
            "Subject",
            "DueDate",
            "DueIn",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ColorID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/Reminders"),
            ("GET", "/Reminders/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="ReservableAmenities",
        client_attr="reservable_amenities",
        model_name="ReservableAmenity",
        fields=(
            "ReservableAmenityID",
            "PropertyID",
            "Name",
            "DisplayName",
            "ColorID",
            "DescriptionRTF",
            "DescriptionHTML",
            "IsActive",
            "IsAllowTWAReservation",
            "IsRequireDisclaimer",
            "IsAutomaticallyApproveRequestsSubmittedOnTWA",
            "IsRequirePaymentForRequestsSubmittedOnTWA",
            "DisclaimerRTF",
            "DisclaimerHTML",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ReservableAmenities"),
            ("GET", "/ReservableAmenities/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="ReservableAmenityAvailabilitySchedules",
        client_attr="reservable_amenity_availability_schedules",
        model_name="ReservableAmenityAvailabilitySchedule",
        fields=(
            "ReservableAmenityAvailabilityScheduleID",
            "ReservableAmenityID",
            "FromDate",
            "ToDate",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ReservableAmenityAvailabilitySchedules"),
            ("GET", "/ReservableAmenityAvailabilitySchedules/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="ReservableAmenityReservationRequests",
        client_attr="reservable_amenity_reservation_requests",
        model_name="ReservableAmenityReservationRequest",
        fields=(
            "ReservableAmenityReservationRequestID",
            "ReservableAmenityID",
            "TenantID",
            "FromDateTime",
            "ToDateTime",
            "Notes",
            "TotalAmountDue",
            "RemainingBalance",
            "CreateWebUserID",
            "CreateUserID",
            "CreateDate",
            "UpdateUserID",
            "UpdateDate",
            "ConcurrencyID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/ReservableAmenityReservationRequests"),
            ("GET", "/ReservableAmenityReservationRequests/{id}"),
            ("POST", "/ReservableAmenityReservationRequests"),
            ("DELETE", "/ReservableAmenityReservationRequests"),
            ("DELETE", "/ReservableAmenityReservationRequests/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="SharedReportBatches",
        client_attr="shared_report_batches",
        model_name="SharedReportBatche",
        fields=(
            "SharedReportBatchID",
            "ReportBatchID",
            "UserID",
            "CustomToolbarGroupID",
            "IsExcludedFromMenu",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/SharedReportBatches"),
            ("GET", "/SharedReportBatches/{id}"),
            ("POST", "/SharedReportBatches"),
            ("DELETE", "/SharedReportBatches"),
            ("DELETE", "/SharedReportBatches/{id}"),
        ),
    ),
    ReferenceMiscResourceSpec(
        path="UnitAmenities",
        client_attr="unit_amenities",
        model_name="UnitAmenity",
        fields=(
            "UnitAmenityID",
            "UnitID",
            "AmenityID",
            "MetaTag",
        ),
        endpoints=(
            ("GET", "/UnitAmenities"),
            ("GET", "/UnitAmenities/{id}"),
            ("POST", "/UnitAmenities"),
            ("DELETE", "/UnitAmenities"),
            ("DELETE", "/UnitAmenities/{id}"),
        ),
    ),
)

REFERENCE_MISC_MODEL_NAMES = tuple(dict.fromkeys(spec.model_name for spec in REFERENCE_MISC_RESOURCE_SPECS))
REFERENCE_MISC_RESOURCE_CLASS_NAMES = tuple(spec.resource_class_name for spec in REFERENCE_MISC_RESOURCE_SPECS)

__all__ = [
    "REFERENCE_MISC_MODEL_NAMES",
    "REFERENCE_MISC_RESOURCE_CLASS_NAMES",
    "REFERENCE_MISC_RESOURCE_SPECS",
    "ReferenceMiscEndpoint",
    "ReferenceMiscMethod",
    "ReferenceMiscResourceSpec",
]
